server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AeroLite?useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

springfox:
  documentation:
    swagger-ui:
      enabled: true
