version: ${version}

spring:
  application:
    name: AeroLite
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

jwt:
  issuer: AeroLite
  expires_in: 30
  allow_expires_in: 360
