server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AeroLite?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:

springfox:
  documentation:
    swagger-ui:
      enabled: true
