version: ${version}

spring:
  application:
    name: AeroLite
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:/mapper/*.xml
